### ISSUE TITLE
Redirecting from an arbitrary url

### ISSUE THREAD

**Issue by bigfoot90** [symfony-cmf/routing-bundle#277]
I need to persist `RouteRedirect`s from an arbitratry url to a content present in database.

For example assume that a content with url `/landing` already exists,
I need to create redirects like this:

url: `/landing/page-1` --> `/articles/category-a/article1`
url: `/landing/page-2` --> `/articles/category-b/article1`
url: `/landing/another/page` --> `/contacts`
url: `/seo-page-a` --> `/products/category-a/article2`
url: `/some/non-existent/path/sub-content` --> `/products/category-b/article2`

Is there any method to handle this in controller? e.g

``` php
$route = new RedirectRoute();
$route->setFromUrl($url);
$route->setRouteTarget($content);

$dm->persist();
```

If not what is the best approach? how can I solve?

Thanks in advance.

**Comment by dbu** [comment]
@dantleech what do you think, is this covered by RoutingAuto or are we missing something?

**Comment by dantleech** [comment]
I think the problem is that you want to create a RedirectRoute at an arbitrary location, in this case I don't think that the RoutingAuto would help - unless the code could work with a route [schema](https://github.com/symfony-cmf/symfony-cmf-docs/pull/743/files#diff-0fba7cb7e90c54309868d917de71b714R21) but as we want to create arbitrary redirect routes, this is seems not to be the case.
