### ISSUE TITLE
[Question] plans for new release

### ISSUE THREAD

**Issue by netbull** [symfony-cmf/routing-bundle#444]
The last release on packagist is from **2018-09-24** and as I see there are many improvements since then, so are there any plans to make a new release soon?

**Comment by dbu** [comment]
thanks for your interest. yes, a new release would be in order. i am trying to wrap up #445 and #446 and will hopefully soon release 2.2.0

**Comment by dbu** [comment]
hm, and #447 to get symfony 5 support. that requires https://github.com/symfony-cmf/Routing/pull/240 - if you have some time to help out with that one, it would help getting the release sooner. we probably need to do something instead of https://github.com/symfony-cmf/Routing/pull/238 that still works with symfony 5, afaik the legacy dispatcher is only in symfony 4.

**Comment by netbull** [comment]
@dbu I tried, but there are so many dependencies to be modified that it will not happen soon...
Just small example:
- this bundle requires `symfony-cmf/routing`
- package `symfonycmf/routing` requires `symfony-cmf/testing`
- package `symfony-cmf/testing` required `doctrine/phpcr-bundle` and `doctrine/phpcr-odm`
- these two packages are not compatible with Symfony 4...

Again this is just small example of the nightmare chain to bump the versions.

However for now it will be just enough to make this bundle deprecation free and compatible with Symfony 4.4, because it breaks badly. Actually it is already fixed by #440, just patch release is needed

**Comment by dbu** [comment]
yeah that rabbit hole is deep indeed :cry: i am currently trying to get a version of jackrabbit that works fine with phpcr-odm so that i can even run tests again.

unfortunately, there are a couple of new features in the bundle so its not a patch version. i will try again tomorrow and if i am not successful then, i will tag a minor version without symfony 5 support.

**Comment by dbu** [comment]
okay, still digging in that rabbit hole (or however the phrase goes)... meanwhile i tagged https://github.com/symfony-cmf/routing-bundle/releases/tag/2.2.0 to at least have the features and improvements we did. symfony 5 support can be a patch release.

**Comment by dbu** [comment]
finally, symfony 5 support is tagged https://github.com/symfony-cmf/routing-bundle/releases/tag/2.4.0 \o/
